export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_ERROR = 'FETCH_NEWS_ERROR';
export const FETCH_TOP_NEWS_SUCCESS = 'FETCH_TOP_NEWS_SUCCESS';
export const FETCH_TOP_NEWS_ERROR = 'FETCH_TOP_NEWS_ERROR';
export const FETCH_SPORTS_NEWS_SUCCESS = 'FETCH_SPORTS_NEWS_SUCCESS';
export const FETCH_SPORTS_NEWS_ERROR = 'FETCH_SPORTS_NEWS_ERROR';
export const FETCH_WORLD_NEWS_SUCCESS = 'FETCH_WORLD_NEWS_SUCCESS';
export const FETCH_WORLD_NEWS_ERROR = 'FETCH_WORLD_NEWS_ERROR';
